import mysql.connector

database_config = {
    "host": "ID367858_storystreak.db.webhosting.be",
    "user": "ID367858_storystreak",
    "password": "storystreakroot1",
    "database": "ID367858_storystreak",
}

# List of topics
topics = [
    "A journey through time travel.",
    "An unexpected friendship between two unlikely characters.",
    "A post-apocalyptic world where nature reigns.",
    "The last person on Earth.",
    "A magical forest with talking animals.",
    "A heist in a futuristic city.",
    "An ancient prophecy that must be fulfilled.",
    "A haunted house with a dark secret.",
    "A detective solving a complex murder case.",
    "A world where everyone has a superpower.",
    "The discovery of a hidden underwater city.",
    "A musician's rise to fame and fall from grace.",
    "An alien invasion and humanity's fight for survival.",
    "A time loop that repeats the same day over and over.",
    "A group of people stranded on a deserted island.",
    "A parallel universe where everything is opposite.",
    "A conspiracy theory that turns out to be true.",
    "A sentient AI struggling with its identity.",
    "A chef in a Michelin-starred restaurant.",
    "A love story set during a war.",
    "A group of friends on a road trip.",
    "A haunted doll with a vengeful spirit.",
    "A mysterious portal to another dimension.",
    "A world where dreams come to life.",
    "A dystopian society controlled by a single corporation.",
    "A young hero on a quest to save their kingdom.",
    "An immortal character watching the world change.",
    "A small town with a dark secret.",
    "A superhero who loses their powers.",
    "A lost treasure hidden in a remote location.",
    "A student discovering they have magical abilities.",
    "A time-traveling love story.",
    "A ghost trying to solve their own murder.",
    "A world without technology.",
    "A writer who can bring their stories to life.",
    "A spaceship crew on a mission to a distant planet.",
    "A cursed object that brings bad luck.",
    "A family's struggle with a supernatural curse.",
    "A secret society with mysterious rituals.",
    "A child's imaginary friend that becomes real.",
    "A forbidden romance between two rival factions.",
    "A scientist experimenting with the laws of physics.",
    "A person who can see the future but can't change it.",
    "A murder mystery set in a medieval castle.",
    "A talking animal who wants to be human.",
    "A group of survivors in a zombie apocalypse.",
    "A world where memories can be bought and sold.",
    "A conspiracy theory involving the moon landing.",
    "A musician's cross-country tour.",
    "A detective with a supernatural partner.",
    "A reclusive artist and their masterpiece.",
    "A time-travel experiment gone wrong.",
    "A secret garden hidden in the city.",
    "A parallel universe where dinosaurs still exist.",
    "A character who can control the weather.",
    "A forbidden love between royalty and a commoner.",
    "A young inventor creating a groundbreaking device.",
    "A spaceship stranded in deep space.",
    "A cursed painting with a haunting presence.",
    "A journalist investigating a corrupt government.",
    "A small town with a history of strange occurrences.",
    "A group of teens solving mysteries in their neighborhood.",
    "A post-apocalyptic library with the last books in the world.",
    "A society where emotions are forbidden.",
    "A character who can communicate with animals.",
    "A futuristic city where technology controls everything.",
    "A chef competing in a high-stakes cooking competition.",
    "A love story between people from different dimensions.",
    "A detective tracking a notorious serial killer.",
    "A musician who can hear the music of the universe.",
    "A dystopian future where creativity is suppressed.",
    "A hidden treasure map in an old family heirloom.",
    "A student at a school for gifted individuals.",
    "A haunted lighthouse on a remote coast.",
    "A child who discovers a magical world in their closet.",
    "A world where humans are extinct, and animals have evolved.",
    "A character with the ability to time-travel only to historical events.",
    "A village with a tradition of storytelling.",
    "A scientist who creates sentient robots.",
    "A time loop during a family gathering.",
    "A ghost trying to right their past wrongs.",
    "A world without color, where one person can see it.",
    "A superhero team with unique powers.",
    "A hidden underground civilization.",
    "A character with the ability to speak to inanimate objects.",
    "A group of survivors in a nuclear fallout shelter.",
    "A world where music has the power to heal.",
    "A journalist uncovering government conspiracies.",
    "A small town with a history of strange occurrences.",
    "A group of teens solving supernatural mysteries.",
    "A post-apocalyptic society where knowledge is power.",
    "A library that contains the secrets of the universe.",
    "A society where everyone wears masks to hide their emotions.",
    "A character who can manipulate dreams.",
    "A detective tracking a criminal mastermind.",
    "A musician composing a symphony that can change the world.",
    "A dystopian future where creativity is suppressed.",
    "A hidden map to a legendary lost city.",
    "A student discovering a hidden world within their school.",
    "A journey through the human mind and consciousness."
]

# Connect to the MySQL database
conn = mysql.connector.connect(**database_config)
cursor = conn.cursor()

# Insert the topics into the existing "topics" table
for topic in topics:
    cursor.execute('INSERT INTO topics (topic) VALUES (%s)', (topic,))

# Commit the changes and close the database connection
conn.commit()
conn.close()